//! Funciones host (`env.*`) que el nodo JIT debe implementar: el emisor
//! referencia cada host por su import name y su firma WASM.

use wasm_encoder::ValType;
/// Funciones host (`env.*`) que el nodo JIT debe implementar.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HostFn {
    PrintInt,
    PrintFloat,
    PrintBool,
    PrintChar,
    PrintStr,
    PrintEnd,
    Now,
    Exit,
    Sleep,
    Trap,
    ParseInt,
    ParseFloat,
    ParseBool,
    StrConcat,
    StrInt,
    StrFloat,
    StrBool,
    StrChar,
    PowNum,
    Fmod,
    Input,
    StrUpper,
    StrLower,
    StrTrim,
    StrContains,
    StrStartsWith,
    StrEndsWith,
    StrIsEmpty,
    StrLength,
    StrEq,
    AnyToString,
    StrRepr,
    IntAbs,
    FloatAbs,
    ArrPush,
    ArrPop,
    ArrShift,
    ArrUnshift,
    ArrIndexOf,
    ArrIncludes,
    ArrJoin,
    ArrReverse,
    ArrToString,
    MathSqrt,
    MathPow,
    MathMin,
    MathMax,
    MathFloor,
    MathCeil,
    MathRound,
    MathRandom,
    MathSin,
    MathCos,
    MathTan,
    MathLog,
    MathRange,
    JsonStringify,
    JsonParse,
    FsExists,
    FsCwd,
    FsReadFile,
    FsWriteFile,
    FsListDir,
    FsMkdir,
    FsRm,
    RecordNew,
    RecordSet,
    RecordGet,
    RecordHas,
    RecordTag,
    RecordLen,
    RecordKeys,
    RecordValues,
    RecordToString,
    HttpGet,
    HttpPost,
    CmxNew,
    CmxSetProp,
    CmxAddChild,
    CmxToString,
    PrintAny,
    AnyMember,
    AnyIndex,
    FnHandle,
    FnToString,
    FnEnter,
    FnExit,
    CallSite,
    /// Canal genérico de funciones host del nodo: `host_call(id, ptr, n) -> i64`
    /// con args empaquetados `[n:i64][(val:i64, tag:i64)*n]`.
    HostCall,
    // Módulo os
    OsPlatform,
    OsArch,
    OsVersion,
    OsHostname,
    OsHome,
    OsTempdir,
    OsCpus,
    OsPid,
    OsUptime,
    OsEnv,
    OsSep,
    OsIsWindows,
    OsIsUnix,
    // Módulo path
    PathJoin,
    PathBasename,
    PathDirname,
    PathExtname,
    PathResolve,
    PathNormalize,
    PathIsAbsolute,
    PathSep,
    // Módulo process
    ProcessArgs,
    ProcessCwd,
    ProcessEnv,
    ProcessExit,
    ProcessPid,
    ProcessPlatform,
    ProcessTitle,
    // Módulo time
    TimeNow,
    TimeSeconds,
    TimeIso,
    TimeDate,
    TimeClock,
    TimeYear,
    TimeMonth,
    TimeDay,
    TimeHour,
    TimeMinute,
    TimeSecond,
    TimeSleep,
    // Módulo random
    RandomRandom,
    RandomInt,
    RandomFloat,
    RandomUuid,
}

impl HostFn {
    pub fn import_name(&self) -> &'static str {
        use HostFn::*;
        match self {
            PrintInt => "print_int",
            PrintFloat => "print_float",
            PrintBool => "print_bool",
            PrintChar => "print_char",
            PrintStr => "print_str",
            PrintEnd => "print_end",
            Now => "now",
            Exit => "exit",
            Sleep => "sleep",
            Trap => "trap",
            ParseInt => "parse_int",
            ParseFloat => "parse_float",
            ParseBool => "parse_bool",
            StrConcat => "str_concat",
            StrInt => "str_int",
            StrFloat => "str_float",
            StrBool => "str_bool",
            StrChar => "str_char",
            PowNum => "pow_num",
            Fmod => "fmod",
            Input => "input",
            StrUpper => "str_upper",
            StrLower => "str_lower",
            StrTrim => "str_trim",
            StrContains => "str_contains",
            StrStartsWith => "str_starts_with",
            StrEndsWith => "str_ends_with",
            StrIsEmpty => "str_is_empty",
            StrLength => "str_length",
            StrEq => "str_eq",
            AnyToString => "any_to_string",
            StrRepr => "str_repr",
            IntAbs => "int_abs",
            FloatAbs => "float_abs",
            ArrPush => "arr_push",
            ArrPop => "arr_pop",
            ArrShift => "arr_shift",
            ArrUnshift => "arr_unshift",
            ArrIndexOf => "arr_index_of",
            ArrIncludes => "arr_includes",
            ArrJoin => "arr_join",
            ArrReverse => "arr_reverse",
            ArrToString => "arr_to_string",
            MathSqrt => "math_sqrt",
            MathPow => "math_pow",
            MathMin => "math_min",
            MathMax => "math_max",
            MathFloor => "math_floor",
            MathCeil => "math_ceil",
            MathRound => "math_round",
            MathRandom => "math_random",
            MathSin => "math_sin",
            MathCos => "math_cos",
            MathTan => "math_tan",
            MathLog => "math_log",
            MathRange => "math_range",
            JsonStringify => "json_stringify",
            JsonParse => "json_parse",
            FsExists => "fs_exists",
            FsCwd => "fs_cwd",
            FsReadFile => "fs_read_file",
            FsWriteFile => "fs_write_file",
            FsListDir => "fs_list_dir",
            FsMkdir => "fs_mkdir",
            FsRm => "fs_rm",
            RecordNew => "record_new",
            RecordSet => "record_set",
            RecordGet => "record_get",
            RecordHas => "record_has",
            RecordTag => "record_tag",
            RecordLen => "record_len",
            RecordKeys => "record_keys",
            RecordValues => "record_values",
            RecordToString => "record_to_string",
            HttpGet => "http_get",
            HttpPost => "http_post",
            CmxNew => "cmx_new",
            CmxSetProp => "cmx_set_prop",
            CmxAddChild => "cmx_add_child",
            CmxToString => "cmx_to_string",
            PrintAny => "print_any",
            AnyMember => "any_member",
            AnyIndex => "any_index",
            FnHandle => "fn_handle",
            FnToString => "fn_to_string",
            FnEnter => "fn_enter",
            FnExit => "fn_exit",
            CallSite => "fn_call_site",
            HostCall => "host_call",
            OsPlatform => "os_platform",
            OsArch => "os_arch",
            OsVersion => "os_version",
            OsHostname => "os_hostname",
            OsHome => "os_home",
            OsTempdir => "os_tempdir",
            OsCpus => "os_cpus",
            OsPid => "os_pid",
            OsUptime => "os_uptime",
            OsEnv => "os_env",
            OsSep => "os_sep",
            OsIsWindows => "os_is_windows",
            OsIsUnix => "os_is_unix",
            PathJoin => "path_join",
            PathBasename => "path_basename",
            PathDirname => "path_dirname",
            PathExtname => "path_extname",
            PathResolve => "path_resolve",
            PathNormalize => "path_normalize",
            PathIsAbsolute => "path_is_absolute",
            PathSep => "path_sep",
            ProcessArgs => "process_args",
            ProcessCwd => "process_cwd",
            ProcessEnv => "process_env",
            ProcessExit => "process_exit",
            ProcessPid => "process_pid",
            ProcessPlatform => "process_platform",
            ProcessTitle => "process_title",
            TimeNow => "time_now",
            TimeSeconds => "time_seconds",
            TimeIso => "time_iso",
            TimeDate => "time_date",
            TimeClock => "time_clock",
            TimeYear => "time_year",
            TimeMonth => "time_month",
            TimeDay => "time_day",
            TimeHour => "time_hour",
            TimeMinute => "time_minute",
            TimeSecond => "time_second",
            TimeSleep => "time_sleep",
            RandomRandom => "random_random",
            RandomInt => "random_int",
            RandomFloat => "random_float",
            RandomUuid => "random_uuid",
        }
    }

    pub(super) fn signature(&self) -> (Vec<ValType>, Vec<ValType>) {
        use HostFn::*;
        let i64p = vec![ValType::I64];
        match self {
            PrintInt | PrintStr => (i64p.clone(), vec![]),
            PrintFloat => (vec![ValType::F64], vec![]),
            PrintBool | PrintChar => (vec![ValType::I32], vec![]),
            PrintEnd => (vec![], vec![]),
            Now => (vec![], vec![ValType::I64]),
            Exit | Sleep => (i64p.clone(), vec![]),
            Trap => (vec![ValType::I64, ValType::I64], vec![]),
            ParseInt | StrInt => (i64p.clone(), vec![ValType::I64]),
            ParseBool => (i64p.clone(), vec![ValType::I32]),
            ParseFloat => (i64p.clone(), vec![ValType::F64]),
            StrFloat => (vec![ValType::F64], vec![ValType::I64]),
            StrBool | StrChar => (vec![ValType::I32], vec![ValType::I64]),
            StrConcat => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            PowNum => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            Fmod => (vec![ValType::F64, ValType::F64], vec![ValType::F64]),
            Input => (vec![], vec![ValType::I64]),
            StrUpper | StrLower | StrTrim | StrLength | StrRepr => {
                (i64p.clone(), vec![ValType::I64])
            }
            StrContains | StrStartsWith | StrEndsWith | StrEq => {
                (vec![ValType::I64, ValType::I64], vec![ValType::I32])
            }
            AnyToString => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            StrIsEmpty => (i64p.clone(), vec![ValType::I32]),
            IntAbs => (i64p.clone(), vec![ValType::I64]),
            FloatAbs => (vec![ValType::F64], vec![ValType::F64]),
            ArrPush | ArrUnshift => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            ArrPop | ArrShift | ArrReverse => {
                (vec![ValType::I64, ValType::I64], vec![ValType::I64])
            }
            ArrIndexOf => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            ArrIncludes => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I32],
            ),
            ArrJoin => (
                vec![ValType::I64, ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            ArrToString => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            MathSqrt | MathFloor | MathCeil | MathRound | MathSin | MathCos | MathTan | MathLog => {
                (vec![ValType::F64], vec![ValType::F64])
            }
            MathPow | MathMin | MathMax => (vec![ValType::F64, ValType::F64], vec![ValType::F64]),
            MathRandom => (vec![], vec![ValType::F64]),
            MathRange => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            JsonStringify => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            JsonParse => (i64p.clone(), vec![ValType::I64]),
            FsExists => (i64p.clone(), vec![ValType::I32]),
            FsCwd => (vec![], vec![ValType::I64]),
            FsReadFile => (i64p.clone(), vec![ValType::I64]),
            FsWriteFile => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            FsListDir | FsMkdir | FsRm => (i64p.clone(), vec![ValType::I64]),
            RecordNew => (i64p.clone(), vec![ValType::I64]),
            RecordSet => (
                vec![ValType::I64, ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            RecordGet => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            RecordHas => (vec![ValType::I64, ValType::I64], vec![ValType::I32]),
            RecordTag => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            RecordLen => (i64p.clone(), vec![ValType::I64]),
            RecordKeys | RecordValues => (i64p.clone(), vec![ValType::I64]),
            RecordToString => (i64p.clone(), vec![ValType::I64]),
            HttpGet => (i64p.clone(), vec![ValType::I64]),
            HttpPost => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            CmxNew => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            CmxSetProp => (
                vec![ValType::I64, ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            CmxAddChild => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            CmxToString => (i64p.clone(), vec![ValType::I64]),
            PrintAny => (vec![ValType::I64, ValType::I64], vec![]),
            AnyMember => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64, ValType::I64],
            ),
            AnyIndex => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64, ValType::I64],
            ),
            FnHandle => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![ValType::I64],
            ),
            FnToString => (i64p.clone(), vec![ValType::I64]),
            FnEnter => (
                vec![ValType::I64, ValType::I64, ValType::I64],
                vec![],
            ),
            FnExit => (vec![], vec![]),
            CallSite => (
                vec![ValType::I64, ValType::I64],
                vec![],
            ),
            HostCall => (vec![ValType::I64, ValType::I64, ValType::I64], vec![ValType::I64]),
            // Módulo os: sin args -> i64 (string) o i32 (bool); env(key) -> i64
            OsPlatform | OsArch | OsVersion | OsHostname | OsHome | OsTempdir
            | OsCpus | OsPid | OsUptime | OsSep => (vec![], vec![ValType::I64]),
            OsEnv => (i64p.clone(), vec![ValType::I64]),
            OsIsWindows | OsIsUnix => (vec![], vec![ValType::I32]),
            // Módulo path
            PathBasename | PathDirname | PathExtname | PathResolve | PathNormalize => {
                (i64p.clone(), vec![ValType::I64])
            }
            PathJoin => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            PathIsAbsolute => (i64p.clone(), vec![ValType::I32]),
            PathSep => (vec![], vec![ValType::I64]),
            // Módulo process
            ProcessArgs | ProcessCwd | ProcessPid | ProcessPlatform | ProcessTitle => {
                (vec![], vec![ValType::I64])
            }
            ProcessEnv => (i64p.clone(), vec![ValType::I64]),
            ProcessExit => (i64p.clone(), vec![]),
            // Módulo time
            TimeNow | TimeSeconds | TimeIso | TimeDate | TimeClock | TimeYear
            | TimeMonth | TimeDay | TimeHour | TimeMinute | TimeSecond => {
                (vec![], vec![ValType::I64])
            }
            TimeSleep => (i64p.clone(), vec![]),
            // Módulo random
            RandomRandom => (vec![], vec![ValType::F64]),
            RandomInt => (vec![ValType::I64, ValType::I64], vec![ValType::I64]),
            RandomFloat => (vec![ValType::F64, ValType::F64], vec![ValType::F64]),
            RandomUuid => (vec![], vec![ValType::I64]),
        }
    }
}
