[package]
name = "clxr"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "clxr"
path = "src/main.rs"

[dependencies]
cls-core = { workspace = true, features = ["wasm-backend"] }
cls-runtime = { workspace = true }
cls-jit = { workspace = true }
zip = "2"
serde_json = "1"
